# Generated by Django 5.0.1 on 2024-02-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serviceBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=50)),
                ('service_heading', models.CharField(max_length=50)),
                ('service_content', models.TextField()),
            ],
        ),
    ]
