# Generated by Django 5.0.1 on 2024-02-29 03:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesinerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebox',
            name='service_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
